nickg/nvc

README.md

Curl isn't installed by default on at least Ubuntu 14.04, but is needed by `tools/fetch-ieee.sh`.

added curl dependency to README.md

---

src/elab.c

For testbenches, I often make a single top-level entity and put each test suite into its own architecture. It's necessary to be able to indicate which architecture I want to simulate. It took only a small tweak to support this. I don't see any tests for the command line interface, so there is no associated testcase.

new feature: allow entity-architecture pair to be specified from the command line

---

src/sem.c
test/sem/issue239.vhd
test/test_sem.c

I noticed that the VITAL library doesn't compile after the fix for #239. It turns out that sem_locally_static() doesn't handle deferred constants correctly (it assumes a constant has a value). In the future, I'll make clean builds from scratch -- not just "make check" to test fixes.

fix that sem_locally_static() didn't handle deferred constants

---

src/sem.c
test/sem/protected.vhd
test/test_sem.c

This implements the fourth (and final) error specified by the LRM for default expressions in interface declarations -- it does not permit a protected type parameter to have a default expression.

add last check similar to those for issue #224

---

src/dump.c

Dump subtypes as "subtype" rather than "type" and reference their base type rather than appearing as a new definition. Also allow dumping of real and enum types/subtypes.
```VHDL
package pkg is
type a1 is array (integer range <>) of character;
subtype sa1 is a1 (1 to 4);
type a2 is array (integer range <>, integer range <>) of character;
subtype sa2 is a2 (1 to 2, 3 to 4);
type e is (one, two, three, four);
subtype se is e (two to four);
type d is ('a', 'e', 'c', 'd');
subtype sd is d ('d' downto 'e');
subtype n is natural range 0 to 4;
subtype r is real range 0.0 to 5.0;
subtype stime is time range 0 ns to 1 ns;
type t  is range 1 to 10;
subtype st is t range 2 to 50;
end package pkg;
```
```
$ nvc -a test.vhd --dump pkg | grep -v predefined
package WORK.PKG is
type WORK.PKG.A1 is array …
```

dump subtypes more explicitly; dump real and enums ranges

---

src/bounds.c
test/bounds/issue247.vhd
test/test_bounds.c

I also modified it to use folded_bounds() for the limits as a step towards supporting checking of enum types here.

rework bounds_check_decl to support DOWNTO. Fixes #247

---

src/dump.c

As the summary says, dump the range for physical subtypes. I also refactored enum subtype dumping to use this same branch.

dump physical subtype range and simplify dumping enum subtype

---

src/bounds.c
test/bounds/bounds2.vhd
test/test_bounds.c

Add bounds-checking for rejection limits, signal assignment delays and for the delay in wait statements.

Bounds check delays

---

src/sem.c
test/sem/const2.vhd
test/test_sem.c

Fixed that the type wasn't getting set from the value supplied in the package body.

Fix that unconstrained deferred constant arrays didn't get their type set

---

src/lexer.l

Modification in lexer in order to handle empty bit string literals and also forcing no underscore in first character

Handling empty Bit String and no underscore in first character

---

tools/run.sh

I couldn't launch test without it.

test/run.sh: fix little bug to launch run.sh in tools directory

---

src/parse.c

It hangs on the following input without the fix.
```vhdl
entity bug is
end entity;
architecture a of bug is
begin
main : process is
begin
end;
end;
```

Fixes drop_tokens_until exit condition

---

tools/fetch-ieee.sh

Hello！
Ieee download webpage has changed.
tools/fetch-ieee.sh doesn't work now.
And needed files are packed in 1076.2-1996_downloads.zip.
I tested new fetch-ieee.sh on my WSL/debian and it seemed to work well.

ieee download webpage has changed

---

README.md

macOS has been spelt macOS rather than OS X since Sierra or something like that, so let's update this.

Rename Mac OS X to macOS

---

src/names.c
src/names.h
src/parse.c
src/simp.c
src/tree.c
test/regress/gold/bounds18.txt
test/regress/gold/bounds19.txt
test/regress/gold/debug3.txt

This MR adds implicit label creation. Processes and Loops are labelled according to VHDL 2008 LRM.
Statements are labelled extra.
Processes are labeled with _PX, where X starts from 0. Statements
equivalent to processes are also labeled. If equivalent process statements
exist in entity, X is not reset in architecture, but it keeps on counting.
Process counter is passed as I_IVAL attribute of T_ENTITY.
Loops are labeled with _LX, where X is reset upon each declarative
scope in which loops can occur (process body or subprogram body).
Statements are labelled with _SX, where X is reset in the same
scenarios as _LX. This-way labels of statements from different
processes do not affect each other.
Labels of statements for concurrent conditional, selected signal
assignment and concurrent …

Implicit labeling

---

src/rt/cover.c

This MR adds a button to the generated Code coverage report which copies
the "exclude" command for respective bins / coverage tag into the clipboard.
Code coverage analysis then can work like so:
1. generate report with empty exclude file passed
2. View the report, get the exclude command, paste it to opened exclude file in IDE / Text editor
3. Regenerate report
4. Go to step 2 again until you have reached 100 % or found something what should not be excluded. In such case, write test which stimulates the situation and gets the code covered.
I have seen this sort of "working model" working for many verification engineers.
I tried to keep the changes simple.
The new button has different CSV style than the buttons for switching tabs. I will tackle that in
next MR where I would like to …

src: Add button to code coverage report to get Exclude command.

---

src/lower.c

I started to look into optimization of coverage and wanted to re-run the NEORV32 test.
The report generation crashed, and as I started to debug it, I figured out that `others` choice on
vectored case statements was not popping coverage scope correctly. Thus, in a complex design,
with many `others` choices on `std_logic_vector`, the coverage scope name eventually accumulated
to so long name, that I was unable to open a new HTML file (due to Linux file name limit) and
the crash occured.
This MR fixes the issue, however I don't have a test for now. I will add another MR where I will
implement option to print summary of each hierarchy into command line as the report is being
generated. Then, I will add a test to check design with multiple hierarchies (and also `others`
choices on vectored …

src: Fix coverage scope pop on case array statements

---

src/rt/cover.c
src/rt/cover.h

Hello,
this PR improves code coverage report generation:
1. Print only name of the instance in instance sub-table (first commit).
2. Optimize querying name of the signal for toggle coverage:
- Approach A - Second commit - Dump separately signal name -> Drawbacks: Prolongs intermediate code generation and bloats COVDB size
- Approach B - Do not track "level" of tag, but track position within `hier` ident where signal / port name starts.
The approach B is better, see the print in the issue related to performance optimizations

Coverage Report Optimizations

---

nvc.1
src/nvc.c
src/rt/cover.c
src/rt/cover.h
test/regress/cover12.sh
test/regress/cover12.vhd
test/regress/gold/cover12.txt
test/regress/testlist.txt

This MR adds basic exclude support on unreachable toggles on instance ports.
Unreachability is remembered in run-time data and checked during report
generation if according CLI option is set. Exclude reason is now placed in
third column of excluded bins to distinguish between the ones coming from
exclude file and automatically excluded bins.
The implementation handles `std_logic` and `std_logic_vector`.
The MR does not handle the cases where part of the port is driven by non-const
value (e.g. single bit of a vector, or single field of a record port).

WIP: Cover exclude unreachable

---

src/parse.c
test/parse/vhdl2019.vhd
www/features.html.in

This allows for optional trailing semicolon on interface lists.

Add parsing changes for LCS-2016-071a.

---

src/parse.c
test/parse/vhdl2019.vhd
test/test_parse.c
www/features.html.in

All interface lists can be ordered.
This allows for entities and subprograms to reference earlier elements in the interface list.

Add parsing changes for LCS-2016-086.

---

src/rt/cover.c

Just more fine-grained macros for code coverage debug. Tracing a real simulation (e.g. NEORV)
with all cover debug options enabled is now not really feasible.

src/cover: Add fine-grained reporting in code coverage.

---

src/parse.c
test/parse/vhdl2019.vhd
test/test_parse.c
www/features.html.in

Makes the `component` keyword at the end of a component declaration optional.

Add LCS-2016-055a (Optional Component Ending).

---

nvc.1
src/nvc.c
src/rt/cover.c

When `--verbose` is set during coverage processing dumps summary of each hierarchy to linked list.
At the end iterates backwards to print the whole summary to std out.

src, www: Add verbose option to Coverage Report generation.

---

src/parse.c

When working with the [all08.vhdl](https://github.com/ghdl/ghdl/blob/c33f41e4612347d1fcbb9a37bc82249d7b8366eb/testsuite/sanity/004all08/all08.vhdl) file from the GHDL repository, there was a parsing error with the following:
```vhdl
attribute user_attr of clear [std_logic_vector]: procedure is true;
```
The LRM states that the `entity_name_list` can be a list of `entity_designator` which could also include a `signature`.  It can also be the keywords `all` or `others`, if they are the last attribute for that particular class in the declarative part.  It's an error if they aren't the last.
With that being said, this gets past the parsing issue because of the other parsing examples in the file, but obviously things aren't correct with the tree entries.
`nvc` subsequently dies later in the …

Update entity name list parsing.

---

NEWS.md
nvc.1
src/lower.c
src/nvc.c
src/rt/cover.c
src/rt/cover.h
src/util.c
src/util.h
test/regress/cover13.sh
test/regress/cover13.vhd
test/regress/data/cover13_spec.txt
test/regress/data/cover9_ef1.txt
test/regress/gold/cover13.txt
test/regress/gold/cover9.txt
test/regress/testlist.txt

This MR adds `coverage-spec` argument to `elaborate`. A coverage specification file shall be passed
to this option. Coverage specification file allows controlling hierarchy / entity names on which coverage
is collected. Following is allowed within coverage specification file:
`(+|-)hierarchy <HIERARCHY>`  - Enables/disables collecting coverage for given hierarchy
`(+|-)block <BLOCK_NAME>`  - Enables/disables collecting coverage for given entity names / block names
Tests and manual edit still to be added in this MR.

src: Add coverage-spec

---

src/lower.c
src/rt/cover.c
src/rt/cover.h
test/regress/cover14.sh
test/regress/cover14.vhd
test/regress/data/cover14_ef1.txt
test/regress/gold/cover14.txt
test/regress/testlist.txt

This MR adds the last part of "exluding unreachable" coverage bins (for now).
Un-reachable expression bins are automatically flagged and excluded in the
generated report. "Unreachability mask" is remembered per-tag and separated
from "exclude mask". Exclude mask is dropped from cov-db, since its meaning
is now only during report generation time.

Coverage expr unreachable

---

src/lexer.l
src/object.c
src/parse.c
src/psl/psl-fsm.c
src/psl/psl-node.c
src/psl/psl-node.h
src/scan.h
test/psl/parse4.vhd
test/psl/parse5.vhd
test/test_psl.c

Adds parsing of `SERE` and `Compound_SERE`. SEREs are parsed recursively. If a SERE
contains chain of SEREs connectd with the same operator (e.g. `{a;b;c;d;e}`) the top most
SERE is a single SERE.

src: Add parsing of Compound SERE

---

src/simp.c
test/regress/cover15.sh
test/regress/cover15.vhd
test/regress/gold/cover15.txt
test/regress/testlist.txt

Adds simple test for conditional expression in the return statement.
Minor source modification diversifies location of newly created `T_RETURN` so that when doing code coverage
analysis, different conditional values are highlighted in the report:
This is the same as if there is a "conditional signal assign", that is converted to sequence of signal assigns
separated by "if" statements. Each new signal assign statement has "loc" corresponding to "result" of
the conditional epression, instead of "loc" from the whole "conditional signal assign" statement.

Cover conditional return test

---

contrib/install-osvvm.tcl

Add a VHDL-2019 compiled installation to OSVVM when installing from nvc.

Adding VHDL-2019 to OSVVM installation.

---

src/rt/cover.c

Just a refactoring how is code coverage report printed:
- Add some CSS styles to reduce size of the generated HTML files. Saves around 17% of the HTML report size.
- Dont print new-lines from the code
- Fix printing one beyond last text buffer character (puts non ASCII rubbish into the HTML)
- Bunch of newlines to make the HTML better readable by human eye.

Cover HTML report enhancements

---

src/lower.c
src/rt/cover.c
src/rt/cover.h

This MR contains bunch of improvements in Code coverage report generation. I tried to focus on clarity of the generated report since it seems to me that current format is not very "self-explaining".
From user perspective following changes:
- Multiline code samples are printed complete (If they are too long, middle lines are skipped)
- Line numbers are shown before the line
- Statement kind is shown. Branch "type/category" is shown. Expression name is shown. 
- For single line expressions, `LHS` and `RHS` hints are given with arrows. This is usefull for nested expressions: 
I hope this helps for better debugability of code coverage. Still, there is a small drawback, that multi-line
source code is printed without any hints. This is OK for long statements or branches (its somewhat
clear what …

Coverage report enhancements

---

contrib/install-vunit.sh

Add VHDL-2019 for VUnit library installation.

Add VHDL-2019 for VUnit library installation.

---

src/cov/cov-data.c
test/regress/cover20.sh
test/regress/cover20.vhd
test/regress/gold/cover20.txt
test/regress/testlist.txt

Adds merging of items and scopes not found in the first coverage DB.

src, test: Fix-up merging of non-matching coverage items and scopes.

---

src/vhpi/vhpi-model.c
test/regress/testlist.txt
test/regress/vhpi10.vhd
test/vhpi/vhpi10.c

Search declarations as well as statements so we can find package instances. This allows VHPI to use signals which have types defined in package instances.

vhpi: Support types from package instances

---

src/jit/jit-priv.h

The mem_initialize procedure in the Lattice MachXO3 behavioural simulation libraries takes more arguments than JIT_MAX_ARGS. Bump JIT_MAX_ARGS a bit so that this procedure elaborates.

Bump JIT_MAX_ARGS

---

nvc.1
src/cov/cov-report.c
test/regress/cover22.sh
test/regress/cover22.vhd
test/regress/gold/cover22.txt
test/regress/testlist.txt

Hi,
this MR is follow-up of issue by @sean-anderson-seco  :
https://github.com/nickg/nvc/issues/823
It handles code coverage report generation when there are multiple scope children in the root
coverage scope. Previously, only first scope was reported.

Cov different top hierarchies

---

src/lexer.l
test/dist.mk
test/parse/basic_identifier.vhd
test/test_parse.c

In the LRM (VHDL-2008 at least) basic identifiers are defined as:
```
basic_identifier ::= letter { [ underline ] letter_or_digit }
```
The LRM defines brackets `[]` as optional elements (regex question mark `?`) and braces `{}` as optional repeated (zero or more, regex asterisk `*`).
For underlines, this means that an identifier must never start with it, end with it, and there must never be more than one underscore in sequence. Before this PR, nvc doesn’t parse basic identifiers according to that definition but permits underscores in any place of an identifier, except for the first position. This patch checks for the proper behavior and also fixes the issue in the parser.
With just 47d0963 applied, `make check` fails. 62c2c0a fixes the issue. Neither verilog nor tcl were enabled, so a …

Fix basic_identifier

---

src/cov/cov-api.h
src/cov/cov-data.c
src/cov/cov-report.c
src/rt/cover.c
test/perf/toggle_cov.vhd

Hi,
this is a MR with some left-overs from previous refactor:
- Couple of bug-fixes that creeped in and were un-recognized since they are related to Coverage report printing that is not checked.
- Removed `flag` from `cover_pair_t` -> Redundant now
- Added run-time saturation also for Toggle Items
- Optimizes toggle items in cases when `count-from-undefined` and `count-from-to-z` are enabled.
- Slightly improves coverage report for PSL assertions
- Added Cover item data into the Coverage report (now that it means how many times an item was covered).
- Added a test for saturation during merging. Testing Saturation on increments during run-time is excessively long.

Cover saturate toggle

---

README.md

This should also assist in auto-building `rpm` distribution files for RPM based package managers such as `dnf`, `yum`, `zypper`, and `yast`, as used by Fedora, CentOS, and OpenSUSE.

Add RPM-based dependencies to README for build-from-source

---

Makefile.am
configure.ac
src/Makemodule.am
test/Makemodule.am

The old code used to detect zlib by trying to compile a program. All well and good, until you want to use a zlib that is not in a standardized location.
This change allows providing zlib via a pkgconfig path.

Use pkg-config to detect zlib

---

NEWS.md
lib/nvc/cover_pkg-body.vhd
lib/nvc/cover_pkg.vhd
nvc.1
src/cov/cov-api.h
src/cov/cov-data.c
src/cov/cov-data.h
src/cov/cov-exclude.c
src/cov/cov-report.c
src/nvc.c
src/rt/cover.c
src/symbols.txt
test/regress/cover25.vhd
test/test_elab.c
test/test_lower.c

Integrates OSVVM functional coverage to NVC functional coverage.
Adds default name for coverage bin if no name is set. This is needed for `CovPType`.
Adds support for changing name on the fly, since OSVVM API has such function,
and user is not forced to first create with name, and only then create cover bins.
Tracks `atleast` as threshold that needs to be reached for bin to be considered as covered.
Range for each bin is tracked. A global `threshold` option is added. Reporting is debugged:
Supports regular and cross bins. E.g.:
```
Cov1 <= NewID("DUMMY NAME") ;
Cov2 := NewID("DUMMY") ;
wait for 0 ns ; -- Update Cov1
AddCross(Cov1, GenBin(0,10000,3), GenBin(0,2), GenBin(0,2));
AddBins(Cov2, "Bin 10 to 12", GenBin(27,10,12,1));
AddBins(Cov2, "Bin 13 to 15", GenBin(13,15));
```
Needs OSVVM: …

OSVVM functional coverage integration

---

NEWS.md
src/option.c
src/option.h
src/sem.c
test/sem/missingwait.vhd
test/test_sem.c
test/unit_test.c

Hi there!
I did (as sadly common) something stupid and my testbench did ... nothing. I recompiled with questa which gave me an nice warning that one of the processes without sensitivitiy list did not contain any wait statements. Aha! - Found the culprit.
So I thought maybe nvc would profit from a similar warning.
Currenty, this breaks some regression checks as they also trigger this warning. Should this be put behind a flag?
Let me know of any comments or nitpicks. I'm happy to change the pr in any way required.
Cheers.

Warn on missing wait

---

NEWS.md
src/names.c
test/parse/issue1038.vhd
test/test_parse.c

The fuzzing done by @avelure produced various interesting errors.
The one I try to fix here seems to stem from a simple typo in the implementation of `warn_hidden_decl`.
I added a testcase but it produces another error `../test/test_util.c:199:F:Core:test_issue1038:0: Assertion 'parse() == NULL' failed` But I don't know exactly why. I do not fully understand the test framework though and could be doing something stupid. 
Cheers

Fix crash on warning of hidden declaration. Issue #1038

---

src/names.c
src/sem.c
test/parse/issue1038.vhd
test/test_parse.c

Continuation of the fuzzing crashes found by @avelure.
See https://github.com/nickg/nvc/issues/1038#issuecomment-2452911050.
This one happened when `type_eq` was called on a `kind` that is actually `NULL`. I added a simple check. The tests with `make check` are passing and seem to indicate that nothing else was impacted. Lets see what CI thinks of it.
I preliminary merged #1048 to build upon the same test case. I'll rebase once that is in master.
Cheers

Add NULL check before calling type_eq.

---

configure.ac
m4/ax_llvm_c.m4

Another attempt at fixing #1043.

MacOS LLVM only requires -L for libzstd

---

src/lexer.l
src/parse.c
src/scan.c
src/scan.h
test/parse/issue1038.vhd
test/test_parse.c

Continuation of the fuzzing crashes found by @avelure.
See https://github.com/nickg/nvc/issues/1038#issuecomment-2452959299.
While parsing an unexpected PSL builtin function in a primary nvc does crash on an assertion. I relaxed the assertion to an if check. If the check fails, then the switch falls-through to the already existing error message.
Cheers

Fix crash on unexpected psl builtin function in primary

---

src/sem.c
test/sem/issue1038.vhd
test/test_sem.c

Continuation of the fuzzing crashes found by @avelure.
See https://github.com/nickg/nvc/issues/1038#issuecomment-2452978464.
Parsing of the illegal range expression is successful but crashes later on. I added a simple semantic check. I don't quite like that the check function now has two boolean flags `allow_range` and `require_range`.  Maybe this could be consolidated into a single flag? Let me know your thoughts about this.
Cheers

Handle invalid use of attribute as range

---

NEWS.md
src/lexer.l
test/parse/hang.vhd
test/test_parse.c

My own instance of an fuzzer found an hang while parsing integers in scientific notation if the factor is zero.
Cheers

Fix parser hang for integers in scientific notation

---

src/lexer.l
src/parse.c
src/psl/psl-fsm.c
src/psl/psl-node.h
src/scan.h
test/regress/gold/psl14.txt
test/regress/psl14.vhd
test/regress/testlist.txt

Hi,
this is a WIP of sequence repetition, not yet ready to be merged.
I would like to discuss how to proceed with the FSM generation. Consider the example below:
```
-- psl cov_1 : cover {a;b}[*2 to 3] report "COVER HIT!";
```
The current code leads to FSM like so:
State 1 serves as skip condition when minimal required number of repetitions were already met.
In state 8, I would need to:
- Move to 1 via epsilon edge since two repetitions were hit
- Move to 9 since I would like to track third repetition from next cycle on.
Both of these are un-guarded. I create 8 -> 9 edge during "repeat" part, so it is not guarded since
checking of "third" repetition is by guard on epsilon 9 -> 10.
The `psl_lower_state` fires an assert, since I have two "default" edges, one `EDGE_NEXT`
and one …

PSL SERE repetition

---

NEWS.md
src/psl/psl-fsm.c
test/regress/gold/psl16.txt
test/regress/psl16.vhd
test/regress/testlist.txt

Implement SERE fusion, upon SERE build use `EDGE_EPSILON` instead of `EDGE_NEXT`
to get boolean expression matching in single cycle.

feat,test(psl): add SERE fusion support.

---

NEWS.md
src/parse.c
src/psl/psl-fsm.c
src/scan.c
test/regress/gold/psl15.txt
test/regress/psl15.vhd
test/regress/testlist.txt

Implement non-consecutive (`[=`) and goto (`[->`) repetition.
Optional wait cycles between each repetition are handled by helper
state where FSM "waits" for next repetition of boolean.
Last repetition in goto is handled by 3 extra states: `aux`, `dead` and `wait`.
The `aux` , `wait` and the last state of the repetition form a loop that keeps the last
repetition state active until another repetition of boolean expression occurs.
Such N + 1 repetition jumps out of the loop into a `dead` state going nowhere.

feat,test(psl): add non-consecutive and goto repetition support.

---

src/common.c
test/parse/protected3.vhd
test/test_parse.c

Another crash, another fix.
In generating the hint for the type mark error, nvc crashed as `class_of` did not handle protected function calls. I tried to fix it by adding `T_PROT_FCALL` and preemptively also adding `T_PROT_PCALL`. At various places in the codebase `T_PROT_FCALL` and `T_FCALL` are treated the same. So I thought that could be done here as well.
Cheers

Fix crash on type mark error for protected func.

---

NEWS.md
src/parse.c
test/parse/hang.vhd
test/test_parse.c

As discussed in https://github.com/nickg/nvc/issues/1038#issuecomment-2509724739, this now generates the error you suggested. I added the check at the place where we call `strtoul`, because it may return `ULONG_MAX` which was previously simply truncated into an `int` (I guess `-1`) and silently ignored.
Cheers

Fix parser hang for bit string literals.

---

src/parse.c
test/parse/protected3.vhd
test/test_parse.c

We crash, we fix.
If a duplicated protected body is parsed while the first body failed to parse correctly, then we crash when trying to get the primary with `tree_primary`. As this is a fallout from previous error(s) I simply added a check.
I'm not sure if you like the use of `assert(error_count() > 0);` (as found multiple times in `sem.c` and `names.c`) also inside `parser.c`, as that would be the first use of it there. 
Thanks.
Ps. Please let me know if I'm creating too many PRs of maybe too-little-value. I definitely don't want to tax your limited spare time.

Fix crash on duplicated protected body.

---

NEWS.md
src/names.c
src/parse.c
test/parse/pkgindecl.vhd
test/test_parse.c

My own instance of a fuzzer (libFuzzer based, [nvc-fuzz](https://github.com/NikLeberg/nvc-fuzz)) found a crash.
If instead of the usual `package <x> is new ...` in an interface a full package definition `package <x> is ... end package;` was given, then parsing did crash.
With the added simple checks, the crash no longer happens and the parser gives the reasonable error of `unexpected end while parsing interface package declaration, expecting new`.
Note: The standard is a bit moot in the definition, but I think to understand it so that generic package in interfaces may only be defined in generic interfaces.
> An interface package declaration declares an interface package that appears in a generic clause. [VHDL2019, Chapter 6.5.5]
But NVC allows them everywhere. E.g. the following is …

Fix crash on package definition in interface decl.

---

src/parse.c
test/parse/issue1091.vhd
test/test_parse.c

Based on crashing fuzzer input `51c4a1798e1f1aeff3711fc660cc9fa9a06c8ab38777c4fb40e79b23e5682add_standalone` from issue #1091.
The added check ensures that only _legal_ formal parts are parsed / present in the tree. Otherwise attribute references could end up in there.
I don't know what really constitutes as _legal_ formal part. I simply ran the testsuite and added all occurring (and seemingly valid) kinds to the switch case block. All others trigger a new error.
```c
case T_RECORD_REF:
case T_ARRAY_REF:
case T_ARRAY_SLICE:
case T_TYPE_CONV:
break;
```
Please let me know if I forgot something.

[Fuzz] Raise error when formal part is illegal.

---

src/parse.c
test/parse/config.vhd
test/test_parse.c

Based on crashing fuzzer input `0c1d01dd6f3aea51f8b086c4c788132486f2bfe6079eb33e89f4e69d39945bc7` from issue #1091.
Previously nvc allowed entity aspect to be non existent even though for such explicit cases I think even the standard requires it to be existent.
> LRM 19 section 7.3.2.1: When a binding indication is used in an explicit configuration specification, it is an error if the entity aspect is absent.

[Fuzz] Raise error when entity aspect is missing in configuration specification.

---

src/eval.c
test/bounds/issue1091.vhd
test/test_bounds.c

Based on crashing fuzzer input `da346642705230c6f2c89b7c0a522d1078c44b3d0dfd5fe52e2859212edd2784` from issue #1091.
The crash happens because `simplify_local` cannot find the missing choice in the aggregate. Bounds checking reports an error for it, but the check is only done afterwards. This adds a check for missing aggregate choices in `eval_possible` and forbids the early evaluation of such erroneous constructs.
Alternatively one could also do the bounds check before the local simplify and only if there were no errors, but I think that would change the code flow in a lot of places and tests.
Cheers

[Fuzz] Fix crash with missing choices in aggregate.

---

src/names.c
test/parse/alias5.vhd
test/test_parse.c

When we have more than one alias of the same name but both with no valid type, then we crash in `get_result_type` that gets called from `try_resolve_name`.
I'm not sure what the implications for this change are. All tests pass though.
Alternatively I did come up with another (less elegant) fix that would at least set the type to `T_NONE` for both the invalid aliases:
```diff
diff --git a/src/parse.c b/src/parse.c
index 8a0ed211..ce115359 100644
--- a/src/parse.c
+++ b/src/parse.c
@@ -7471,18 +7471,17 @@ static void p_alias_declaration(tree_t parent)
}
tree_set_type(t, type);
}
-   else if (value_kind == T_REF && tree_has_ref(value)) {
+   else if (value_kind == T_REF && tree_has_ref(value)
+            && is_design_unit(tree_ref(value))) {
// A nonobject alias may be a design unit which …
```

[Fuzz] Fix crash with duplicate aliases in name resolution.

---

src/inst.c

Given some combination of procedure with invalid generics and a later instantiation thereof, nvc would crash.
One possible input that triggered the crash would be:
```vhd
package pack2 is
procedure generate_clock
generic (
package inner is
end package;
) is begin
end procedure;
procedure generate_clock2 is new generate_clock;
end package;
```
But I dunno, but for me that looked way too contrived and broken to be worth to put a test for that.
But preventing the crash seemed worthwhile.

[Fuzz] Fix crash when new instance with generics is created.

---

src/parse.c
test/parse/vhdl2008.vhd
test/test_parse.c

As discussed in #1108, this adds your suggested check for `kind == T_GENERIC_DECL`.

[Fuzz] Fix crash with type interface in function parameters. Issue #1108

---

src/names.c
test/parse/alias5.vhd
test/test_parse.c

Very similar to #1106. When we have two aliases that overload each other/are a duplicate but have both an invalid type (it is actually not set at all), then we crash.
Alternatively to this suggested changes, the fix described in the pr comment in #1106 would also prevent the crash happening.
Cheers.

[Fuzz] Fix crash in overload check of invalid alias declarations

---

src/parse.c
test/parse/gensub.vhd
test/test_parse.c

This fixes the following crash that happens on a fallout from parsing error. The tree object returned by `p_name` is of kind `T_ALL` which does not have an identifier.
```
nvc --std=08 -a --relaxed look.vhd 
** Error: expecting uninstantiated subprogram name
> look.vhd:2
|
2 |     procedure foo is new bar.all;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
** Fatal: tree kind T_ALL does not have item I_IDENT
> look.vhd:2
|
2 |     procedure foo is new bar.all;
|                          ^^^^^^^
[0x55c540231eb0] ../src/object.c:255 object_lookup_failed
diag_emit(d);
-->    show_stacktrace();
fatal_exit(EXIT_FAILURE);
[0x55c5401e5592] ../src/tree.c:553 tree_ident
{
-->    item_t *item = lookup_item(&tree_object, t, I_IDENT);
assert(item->ident != NULL);
[0x55c5401c1876] ../src/parse.c:7262 …
```

[Fuzz] Fix crash with instantiation of unexpected kind

---

src/names.c
test/parse/aggregate2.vhd
test/test_parse.c

If an aggregate field name happened to be parsed into an attribute, then solving the type for `others` crashed.
```vhd
package tick is
type t_data_segment is record end record;
constant C_SEGMENT_RECORDS : t_data_segment := (
data'last => (others => '0')
);
end package;
```
```
root@nvc:/workspaces/nvc/fuzz# nvc --std=19 -a --relaxed ../test/parse/aggregate2.vhd 
** Error: no visible declaration for DATA
> ../test/parse/aggregate2.vhd:6
|
6 |     data'last => (others => '0')
|     ^^^^
** Fatal: tree kind T_ATTR_REF does not have item I_REF
> ../test/parse/aggregate2.vhd:6
|
6 |     data'last => (others => '0')
|     ^^^^^^^^^
[0x55666c453ea9] ../src/object.c:255 object_lookup_failed
diag_emit(d);
-->    show_stacktrace();
fatal_exit(EXIT_FAILURE);
[0x55666c40bc32] ../src/tree.c:1004 …
```

[Fuzz] Fix crash with invalid aggregate field name

---

src/common.c
test/parse/aggregate2.vhd
test/test_parse.c

If we try to resolve the bounds of an array aggregate where the index/range type is invalid, we crash. This adds a small check to prevent the crash.
```vhd
package pkg is
type narr is array (t_direction range <>) of natural;
constant C : narr := (others => 0);
end package;
```
```
root@nvc:/workspaces/nvc/fuzz# nvc --std=08 -a --relaxed range.vhd 
** Error: no visible declaration for T_DIRECTION
> range.vhd:2
|
2 |   type narr is array (t_direction range <>) of natural;
|                       ^^^^^^^^^^^
** Fatal: invalid type kind T_NONE in range_of
[0x5636fb65386a] ../src/diag.c:1053 diag_femit
if (d->stacktrace)
-->          show_stacktrace();
}
[0x5636fb653a51] ../src/diag.c:1078 diag_emit
const diag_level_t stderr_level = opt_get_int(OPT_STDERR_LEVEL);
-->    diag_femit(d, d->level …
```

[Fuzz] Fix crash with invalid range type for aggregate

---

NEWS.md
src/common.c
src/lower.c
src/parse.c
src/sem.c
test/regress/issue1125.vhd
test/regress/issue430.vhd
test/regress/testlist.txt

I had a bit of fun trying to fix issue #1125 as it seemed rather simple.
The basic stuff works. But some other does not:
- I had trouble supporting both, the normal label and the alternative label at the same time. Because the current code overwrites the ident of the generate block if an alternative label was found. In such a case `gen_case` and `gen_case_true` would both resolve to `gen_case_true`.
- Interesting to think about what we would even return for the `gen_for` label if we are outside the loop. Inside we have `gen_for(0)`, `gen_for(1)`, etc. But outside? Only `gen_for`?
- I tested this with modelsim and it returns whatever it wants.... sometimes `gen_for(1)` and sometimes `gen_for`. So it does not seem very important.
Let me know if you see another way of implementing it. Please …

Add support for `'*_name` attributes of generate block label

---

NEWS.md
src/sem.c
test/parse/issue1091b.vhd
test/test_parse.c

Based on crashing fuzzer input `a04900efaed84ebf347d7c8325e5bf9fd96b67deb31508d4149b17b558e703c0_standalone` from issue #1091.
If a procedure (or function) is called with too many named arguments, then `sem_check_call_args` asserts that an error in overload resolution must have been reported. But that may not always be the case.
The output of the new error is as follows:
```
** Error: subprogram MEMORYTABLECORRUPTMASK [INTEGER] has no parameter named ENABLEINDEX
> ../test/parse/issue1091b.vhd:17
|
4 |     PROCEDURE MemoryTableCorruptMask (
|     ^ subprogram defined here
...
17 |             EnableIndex => EnableIndex
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^ error occurred here
```
Note: As the crash is depending on `error_count()` returning 0, I put it into a standalone test.
Cheers

[Fuzz] Fix crash with call with too many named arguments. Issue #1091

---

src/vhpi/vhpi-model.c

I stumbled over this earlier, figured it must be a mistake?

Replace redundant copy of libraryName with missing copy of modelName

---

src/psl/psl-lower.c
test/psl/sem2.vhd
test/regress/gold/psl19.txt
test/regress/psl19.vhd
test/regress/testlist.txt
test/test_psl.c
www/features.html.in

Extends PSL `prev()` with second argument that is higher than 1.
The implementation is naive. A "shift register" is maintained for each `prev()` call.
Depth of shift register is given by value of `Number`. Upon even update, the
shift register is shifted towards LSB. LSB is the result value of the function call.
A better implementation would have ring buffer with head pointer. I assume that
the `Number` value is small (couple of cycles at most) so amount of copying is not
excessive.

Extend PSL prev with configurable cycle count.

---

src/cov/cov-report.c
test/regress/cover26.sh
test/regress/cover26.vhd
test/regress/gold/cover26.txt
test/regress/testlist.txt

Brought-up the previous branch with fixes of cover report hierarchy exceeding 256 characters.
Sub-hierarchy path is hashed to create unique hierarchy report name.

Cover fix long report names

---

src/common.c
test/sem/file.vhd
test/test_sem.c

The fuzzer noticed, that if a file type is given an index constraint, then nvc crashes. This fixes that.
Cheers

[Fuzz] Fix crash with index constraint on file type

---

NEWS.md
src/parse.c
src/psl/psl-lower.c
test/regress/gold/psl20.txt
test/regress/psl20.vhd
test/regress/testlist.txt
www/features.html.in

A follow-up to the previous merge-request.
The PSL `prev` logic is abstracted to separate function and used to build logic
for `rose`, `fell` and `stable` as suggested by PSL spec:
```
The function rose() can be expressed in terms of the built-in function prev() as follows: For any bit
expression e and any Boolean c, rose(e,c) is equivalent to the Verilog or SystemVerilog expression
(prev(e,1,c)==1’b0 && e==1’b1), and is equivalent to the VHDL expression (prev(e,1,c)
=’0 and e=’1). The function rose() may be used anywhere a Boolean is required.
```

implement rose, fell and stable PSL built-in functions.

---

src/lexer.l
src/scan.c
src/scan.h
src/vlog/vlog-parse.c
src/vlog/vlog-pp.l
test/test_vlog.c
test/vlog/defaultnettype.v

I tried analysing the xpm models provided with vivado just to see how far I could get and the `default_nettype` is the first problem it encounters.
I tried to add just enough logic to parse the directive correctly but I have no idea how to use the parsed information so this is ad far as I can go for the moment.
According to what I found online this is the notation:
```
`default_nettype wire | tri | tri0 | tri1 | wand | triand | wor | trior | trireg | uwire | none
```

Add parsing of compiler directive `default_nettype

---

NEWS.md
nvc.1
src/cov/cov-report.c
src/rt/cover.c

1. Fixes toggle coverage data being displayed as negative in the coverage report. When driven by constant, highest bit of data holds the unreachability flag, needs to be masked out otherwise value shown in the report is INT32_MIN.
2. Extend manual with explanation of other source of unreachability -> Was missing second source
3. For `--count-from-undefined` allows `X` as undefined value -> Usefull when bus is driven to a valid value only around
the clock edge when it shall be sampled and driven to X otherwise. For such BFM, the toggle coverage will never be
reached since all transitions are from / to X

Coverage minor fixes

---

src/cov/cov-report.c

Fix sorting of coverage data in summary tables.
By converting anything NaN to -1, such row becomes last even if there is a row that has 0 %.

fix coverage report table sorting with N/A, #1179

---

test/test_jit.c

Causes `test_jit.c` compile failure on RHEL8 (gcc version 8.5.0 20210514 (Red Hat 8.5.0-22) (GCC)

fix missing END_TEST in last test_jit test.

---

NEWS.md
src/sem.c
test/sem/ports.vhd
test/test_sem.c

If one did something like this:
```vhd
entity test is end test;
architecture open_actual of test is
begin
process is
procedure test (constant c: natural) is begin end procedure;
begin
test(open);
end process;
end architecture;
```
NVC crashed (quite spectacularly with the colorful jit code dump) during elaboration. I.e. `nvc -a test.vhd` worked great, but `nvc -e test` crashed.
I added a simple semantic check for that:
```
** Error: OPEN actual for formal parameter C without default value
> ../test/sem/ports.vhd:451
|
448 |         procedure test (constant c: natural) is begin
|                                  ^ C declared here
449 |         end procedure;
450 |     begin
451 |         test(open);
|              ^^^^ error occurred here
```
GHDL and ModelSim report the error as:
``` …
```

Fix crash with open actual for formal without default

---

src/rt/structs.h

Fixes some warnings compiling with GCC 10.

Use GCC-friendly syntax for VLSs

---

NEWS.md
nvc.1
src/cov/cov-api.h
src/cov/cov-data.c
src/nvc.c

Adds `--merge-mode` option to `--cover-merge` option.
Allows `intersect` merging where items that are not located in the old DB will
not be taken into account from the newDB.

add --merge-mode option

---

src/lexer.l
src/scan.c
src/scan.h
src/vlog/vlog-parse.c
test/test_vlog.c
test/vlog/param2.v

Add changes to parse parameters inside `#()` for a module declaration.

Parse ANSI parameters declaration

---

NEWS.md
src/cov/cov-data.c
src/cov/cov-report.c
src/nvc.c
test/regress/gold/cover2.xml
test/regress/gold/cover25.xml
test/regress/gold/issue909.txt
test/regress/gold/issue941.xml

This MR copies each source file to a stand-alone HTML file when generating code coverage report.
The generated HTML file is then referenced from the "File" in the coverage hierarchy header.
This is usefull when e.g. a regression is run in CI, and code coverage report is extracted in artifacts.
After downloading the artifacts, the reference to the source files remains valid.
To do this, I needed to track location of the underlying "unit" for the scope, not the "instance".
It affects the XML file output, but I guess this is no big deal since this format is subject to change.
The issue909 also now gives more relevant output since the source file for instance itself can't be found.

Cover embed source files

---

src/lexer.l
src/vlog/vlog-number.c
test/test_vlog.c
test/vlog/integers1.sv

* Accept and parse upper case letters for integer constants radix
* Accept spaces between size and radix as well as between radix and number
* Accept '?' as a z digit

Improve parsing of integer constants
