- src/sem.c
- test/sem/issue224.vhd
- test/test_sem.c
In addition to the signal checks described in the initial issue, I lumped in a similar fix for variable parameters.
> updates for Issue #224

- src/bounds.c
- src/common.c
- src/sem.c
- src/type.c
- test/bounds/bounds.vhd
- test/sem/array.vhd
- test/test_bounds.c
- test/test_sem.c
This eliminates the TODOs in bounds.c relating to enums.
> Add enum bounds checking

- src/parse.c
- src/sem.c
- test/sem/interfaces.vhd
- test/test_sem.c
> add more interface checks

- src/sem.c
- test/sem/array.vhd
- test/sem/file.vhd
- test/sem/file_and_access.vhd
- test/sem/procedure.vhd
- test/sem/protected2.vhd
- test/sem/record.vhd
- test/test_sem.c
Added semantic checks for declarations relating to the use of access, protected, and file types. Details are in the commit logs...
> Add declaration semantic checks

- configure.ac
> Add more FST configure options.

- lib/ieee/Makemodule.am
> Fix a typo.

- src/array.h
- src/cgen.c
> Fix for following warnings.

- src/cgen.c
> Fix for issue #279.

- src/rt/jit.c
> Fix for issue #280.

- src/parse.c
- test/regress/issue284.vhd
- test/regress/testlist.txt
> allow file in package body. fixes issue 284

- src/sem.c
- test/lower/access_bug.vhd
- test/test_lower.c
Add implicit dereference of record types.
> Acess Types for Records

- test/run_regr.rb
> Use correct NVC_CYG_LIB.

- tools/fetch-ieee.sh
> use github instead of gna! for vital libs download

- src/parse.c
- src/sem.c
- test/sem/issue188.vhd
- test/test_sem.c
I have not read the LRM but it works on all other simulators.
> Fix impure function sem check

- src/eval.c
Allocate memory for eval state as needed, rather than using a single 16KB piece of memory.  Fixes issue #401.
> Allocate memory for eval state as needed

- thirdparty/cpustate.c
There are actually 32 GPR on POWER architecture.
> Fix off by one for FreeBSD/powerpc*

- src/names.c
- src/parse.c
- src/simp.c
- test/test_parse.c
Removal of implicit labelling of branches and statements from parser.
> Remove statement labelling

- src/parse.c
- test/parse/vhdl2019.vhd
- test/test_parse.c
- www/features.html.in
Add VHDL-2019 empty record parsing and tests.
> Adding VHDL-2019 empty record (LCS-2016-082).

- src/parse.c
- src/tree.h
- test/parse/vhdl2019.vhd
- test/test_parse.c
- www/features.html.in
This allows a function to know the return type.
> Add LCS-2016-072b feature

- test/parse/vhdl2019.vhd
- test/test_parse.c
- www/features.html.in
Functionality was previously created.
> Add LCS-2016-006f test and status.

- src/cgen.c
- src/elab.c
- src/lower.c
- src/lower.h
- src/nvc.c
- src/phase.h
- src/prim.h
- src/rt/cover.c
- src/rt/cover.h
- src/rt/model.c
- src/rt/model.h
- test/test_elab.c
- test/test_lower.c
Rename "tag" to "item", and "tagging" to "ctx".
> src, test: Refactoring of cover. 

- nvc.1
Fix a few errors I noticed while reading about FSM coverage.
> Fix some typos and grammatical errors in documentation

- src/cov/cov-data.c
Rework cover item merging within single scope.
Instead of two nested iterations from first item in both new and old scope,
track the first item to be them most likely item in the other scope.
If the items within the scopes are equal, then it is just one iteration.
For each new item non-existing in the old scope, re-iterate with wrapping
to the old scope. Track offset and do correction so that if non-existing item
occurs, the iteration accross new scope is not thrown-off.
I have tried this on NEORV32 with `--include-mems` (to get some coverage scope that has many items),
and merged two different runs. Performance gain is approx 20X.
> src: optimize coverage item merging in single scope.

- m4/ax_llvm_c.m4
Adding LDFLAGS for zstd from pkg-config to resolve issue https://github.com/nickg/nvc/issues/1046
> Fix for https://github.com/nickg/nvc/issues/1046 on macos

- NEWS.md
- src/cov/cov-report.c
Fixes https://github.com/nickg/nvc/issues/1154
> fix missing functional coverage when summing subhierarchies.

- src/lexer.l
- src/scan.c
- src/scan.h
- src/vlog/vlog-node.c
- src/vlog/vlog-node.h
- src/vlog/vlog-parse.c
- test/test_vlog.c
- test/vlog/parse1.v
Hi,
seeing the latest progress you have made in the Verilog parsing, I am trying to parse some SRAM models.
I can't share these, unfortunately. I will try to provide again an issue with link to something public.
> parse verilog event declaration and event trigger.

- src/lexer.l
- src/scan.c
- src/scan.h
- src/vlog/vlog-parse.c
- test/vlog/specify1.v
Resolves last error to fully parse:
https://github.com/IHP-GmbH/IHP-Open-PDK/tree/dev/ihp-sg13g2/libs.ref/sg13g2_sram/verilog
> parse verilog timing check condition.

- src/vlog/vlog-parse.c
- src/vlog/vlog-sem.c
- test/test_vlog.c
- test/vlog/initial1.v
- test/vlog/tfcall1.v
- Fix parsing  of labels and error check them for initial/fork blocks
- Fix function/tasks definitions and calls when parenthesis are used with no arguments
> Fixup  initial/fork blocks and empty function/task calls
